spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver         # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud01?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    dbcp2:
      min-idle: 5                                       # 最小连接数
      initial-size: 5                                   # 初始连接数
      max-total: 5                                      # 最大连接数
      max-wait-millis: 200  
      
#整合mybatis
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml     # mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                    # mapper映射文件

eureka:
  client:                                               # 客户端注册Eureka的服务列表
    service-url:
      defaultZone: http://localhost:7001/eureka        # 单机版
  instance:
    instance-id: dept-8001             #自定义服务名称地址
    prefer-ip-address: true                             #访问路径可以显示IP地址

info:
  app.name: microservicecloud01
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring:
  profiles: test
  application: 
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver         # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud02?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    dbcp2:
      min-idle: 5                                       # 最小连接数
      initial-size: 5                                   # 初始连接数
      max-total: 5                                      # 最大连接数
      max-wait-millis: 200  
      
#整合mybatis
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml     # mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                    # mapper映射文件

eureka:
  client:                                               # 客户端注册Eureka的服务列表
    service-url:
      defaultZone: http://localhost:7001/eureka        # 单机版
  instance:
    instance-id: dept-8001             #自定义服务名称地址
    prefer-ip-address: true                             #访问路径可以显示IP地址

info:
  app.name: microservicecloud01
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
       